# Generated by Django 2.0.7 on 2018-07-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedServiceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.FloatField()),
                ('drift', models.FloatField()),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computed_time', to='Service.Service')),
            ],
        ),
    ]
