# Generated by Django 2.0.7 on 2018-07-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0002_service_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedServiceTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('probability', models.IntegerField()),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computed_time', to='Service.Service')),
            ],
        ),
    ]
