# Generated by Django 2.0.7 on 2018-07-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputedServiceTime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedservicetime',
            name='probability',
        ),
        migrations.RemoveField(
            model_name='computedservicetime',
            name='time',
        ),
        migrations.AddField(
            model_name='computedservicetime',
            name='ave',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computedservicetime',
            name='drift',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computedservicetime',
            name='std',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computedservicetime',
            name='var',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
