# Generated by Django 2.0.7 on 2018-07-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComputedServiceTime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedservicetime',
            name='Service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computed_time', to='Service.Service'),
        ),
    ]
