# Generated by Django 2.0.7 on 2018-07-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0004_auto_20180707_1055'),
        ('Service', '0002_service_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=False)),
                ('passcode', models.CharField(max_length=64)),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teller', to='Employee.Employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teller', to='Service.Service')),
            ],
        ),
    ]
