# Generated by Django 2.0.7 on 2018-07-18 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Transaction', '0001_initial'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification UUID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teller', to='Service.Service')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teller', to='Transaction.Transaction')),
            ],
        ),
    ]
