# Generated by Django 2.0.7 on 2018-07-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teller',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
