# Generated by Django 2.0.7 on 2018-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teller',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
