# Generated by Django 2.0.7 on 2018-07-10 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teller', '0002_teller_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teller',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='teller',
            name='passcode',
        ),
        migrations.AddField(
            model_name='teller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification UUID'),
        ),
    ]
