# Generated by Django 2.0.7 on 2018-07-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0006_auto_20180714_1440'),
        ('Teller', '0003_auto_20180710_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='teller',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teller', to='Transaction.Transaction'),
        ),
    ]
