# Generated by Django 2.0.7 on 2018-07-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teller', '0005_teller_priority_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teller',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teller', to='Transaction.Transaction'),
        ),
    ]
