# Generated by Django 2.0.7 on 2018-07-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teller', '0006_auto_20180716_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teller',
            old_name='priority_number',
            new_name='teller_number',
        ),
    ]
