# Generated by Django 2.0.7 on 2018-07-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0003_remove_service_computed_service_time'),
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('complaint', models.TextField(max_length=500)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='Service.Service')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='Transaction.Transaction')),
            ],
        ),
    ]
