# Generated by Django 2.0.7 on 2018-07-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='uploads/profile_pic/default.png', upload_to='uploads/profile_pic/'),
        ),
    ]
