# Generated by Django 2.0.7 on 2018-07-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20180707_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
