# Generated by Django 2.0.7 on 2018-07-07 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0004_auto_20180707_1055'),
        ('Service', '0002_service_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification UUID')),
                ('time_started', models.DateTimeField(null=True)),
                ('time_ended', models.DateTimeField(null=True)),
                ('computed_time', models.IntegerField()),
                ('time_joined', models.DateTimeField(auto_now_add=True)),
                ('priority_num', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='Employee.Employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='Service.Service')),
            ],
        ),
    ]
