# Generated by Django 2.0.7 on 2018-07-18 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Skipped'), ('C', 'Cancel'), ('A', 'Available'), ('CP', 'Completed')], default='A', max_length=2)),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='Unique Verification UUID')),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('computed_time', models.IntegerField()),
                ('time_joined', models.DateTimeField(auto_now_add=True)),
                ('priority_num', models.CharField(max_length=20)),
                ('log', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='Service.Service')),
            ],
        ),
    ]
