# Generated by Django 2.0.7 on 2018-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('S', 'Skipped'), ('C', 'Cancel'), ('A', 'Available'), ('CP', 'Completed'), ('R', 'Reserved')], default='A', max_length=2),
        ),
    ]
