# Generated by Django 2.0.7 on 2018-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_remove_transaction_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='log',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
