# Generated by Django 2.0.7 on 2018-07-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_auto_20180720_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='when_to_notify',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
