# Generated by Django 2.0.7 on 2018-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_auto_20180721_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='when_to_notify',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
