# Generated by Django 2.0.7 on 2018-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_transaction_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='in_line',
            field=models.BooleanField(default=True),
        ),
    ]
