# Generated by Django 2.0.7 on 2018-07-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_transaction_in_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='in_line',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('S', 'Skipped'), ('C', 'Cancel'), ('A', 'Available'), ('CP', 'Completed')], default='A', max_length=2),
        ),
    ]
