# Generated by Django 2.0.7 on 2018-07-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_auto_20180722_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='when_to_notify',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
