# Generated by Django 2.0.7 on 2018-07-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_auto_20180727_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mac',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
    ]
