# Generated by Django 2.0.7 on 2018-07-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_auto_20180714_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
