# Generated by Django 2.0.7 on 2018-07-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128)),
                ('computed_service_time', models.DurationField(blank=True)),
            ],
        ),
    ]
