# Generated by Django 2.0.7 on 2018-07-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_service_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='computed_service_time',
        ),
    ]
