# Generated by Django 2.0.7 on 2018-07-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
    ]
